export const IOEvent = Object.freeze({
    START_FILE_TRANSFER_AS_CLIENT: 'IOTypes.START_FILE_TRANSFER_AS_CLIENT',
    READ_FILE_AS_CLIENT: 'IOTypes.READ_PAYLOAD_BY_CLIENT',
    CREATE_FILE_AS_SERVER: 'IOTypes.CREATE_FILE_BY_SERVER',
    WRITE_PAYLOAD_AS_SERVER: 'IOTypes.WRITE_PAYLOAD_BY_SERVER',
    HANDLE_FILE_END: 'IOTypes.CHECK_FILE_SIZE_BY_SERVER',
});
